version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11

    working_directory: ~/ma-perma

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build
      - run: npm test -- --coverage

      - deploy:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | sudo python
              sudo apt-get install python-dev
              sudo pip install awscli
              aws --region eu-central-1 s3 sync build s3://ma-perma.org --delete
            else
              echo "Not master branch so not deploying"
            fi

